export const siteData = {
  brand: {
    name: 'LexAssist',
    accent: 'Assist',
    shortDescription: 'Trusted online legal help, accessible to everyone.',
    copyrightText: '© 2025 LexAssist - Trusted Online Legal Help. All rights reserved.',
  },
  navigation: {
    links: [
      { label: 'Home', href: '/#home' },
      { label: 'Services', href: '/#services' },
      { label: 'Lawyers', href: '/#lawyers' },
      { label: 'About', href: '/#about' },
      { label: 'Contact', href: '/#contact' },
    ],
    ctaLabel: 'Book Appointment',
  },
  home: {
    hero: {
      tag: 'Trusted Legal Platform',
      title: ['Trusted Online', 'Legal Help'],
      description: 'Expert legal consultation, documentation, and case guidance from the comfort of your home.',
      primaryCta: 'Book Appointment',
      secondaryCta: 'Meet Our Lawyers',
      stats: [
        { value: '500+', label: 'Cases Won' },
        { value: '50+', label: 'Expert Lawyers' },
        { value: '10K+', label: 'Happy Clients' },
      ],
    },
    services: [
      { icon: 'fas fa-users', title: 'Family Law', desc: 'Divorce, custody, adoption' },
      { icon: 'fas fa-gavel', title: 'Criminal Law', desc: 'Bail, FIR, trial' },
      { icon: 'fas fa-home', title: 'Property Law', desc: 'Sale deed, disputes' },
      { icon: 'fas fa-building', title: 'Corporate Law', desc: 'Contracts, compliance' },
      { icon: 'fas fa-scale-balanced', title: 'Civil Disputes', desc: 'Recovery, injunctions' },
      { icon: 'fas fa-file-signature', title: 'Documentation', desc: 'Affidavits, notices' },
      { icon: 'fas fa-file-lines', title: 'Legal Notice', desc: 'Draft and send' },
      { icon: 'fas fa-file-pen', title: 'Affidavit Drafting', desc: 'Notarized format' },
      { icon: 'fas fa-file-contract', title: 'Agreement Drafting', desc: 'Rent, employment' },
      { icon: 'fas fa-calendar-check', title: 'Appointment Letter', desc: 'Official letter' },
    ],
    why: [
      { icon: 'fa-check-circle', title: 'Trusted Lawyers', desc: 'Verified and experienced professionals' },
      { icon: 'fa-clock', title: 'Fast Appointments', desc: 'Confirmation within 24 hours' },
      { icon: 'fa-lock', title: 'Secure Documents', desc: 'End-to-end encrypted storage' },
      { icon: 'fa-headset', title: 'Online Support', desc: 'Chat and call available' },
    ],
    lawyers: [
      {
        name: 'Adv. Sarah Mehta',
        specialty: 'Family and Corporate Law',
        exp: 12,
        rating: 4.7,
        stars: [1, 1, 1, 1, 0.5],
        barCouncil: 'DEL/1234/2012',
        practice: 'Family, Corporate, Documentation',
        fee: 'Rs. 3,500/session',
        slots: 'Mon-Fri 10AM-4PM',
      },
      {
        name: 'Adv. Rohan Khanna',
        specialty: 'Criminal and Property Law',
        exp: 9,
        rating: 5,
        stars: [1, 1, 1, 1, 1],
        barCouncil: 'MAH/789/2015',
        practice: 'Criminal, Property, Civil',
        fee: 'Rs. 4,000/session',
        slots: 'Tue-Sat 2PM-8PM',
      },
      {
        name: 'Adv. Priya Sharma',
        specialty: 'Corporate and Documentation',
        exp: 14,
        rating: 4.9,
        stars: [1, 1, 1, 1, 1],
        barCouncil: 'KAR/456/2010',
        practice: 'Corporate, Agreements',
        fee: 'Rs. 5,000/session',
        slots: 'Mon, Wed, Fri 9AM-1PM',
      },
    ],
    testimonials: [
      { text: 'LexAssist made my property dispute so easy. The lawyer was very knowledgeable.', name: 'Amit G.' },
      { text: 'Quick appointment and professional documentation. Saved me hours of research.', name: 'Neha S.' },
      { text: 'Affordable and transparent. The online consultation was just like meeting in person.', name: 'Vikram R.' },
    ],
    faqs: [
      { q: 'How do I book a consultation?', a: 'Click Book Appointment, fill the Google Form, and receive a confirmation email within 24 hours.' },
      { q: 'Are the lawyers verified?', a: 'Yes, we verify bar council registration numbers and years of experience before listing any lawyer.' },
      { q: 'What about document security?', a: 'All uploaded files are encrypted and stored securely. We never share your documents with third parties.' },
      { q: 'What modes are available?', a: 'You can choose online video consultation or offline in-person consultation when filling the form.' },
    ],
    contact: {
      address: '123 Legal Square, New Delhi, India',
      phone: '+91 11 2345 6789',
      email: 'support@lexassist.in',
      hours: 'Mon-Fri 9AM - 8PM',
    },
    about: {
      title: 'About LexAssist',
      description: 'We are an online legal platform bridging clients and trusted lawyers. Our mission is to make legal help accessible, transparent, and efficient.',
    },
  },
  appointment: {
    googleFormUrl: 'https://forms.gle/FZiQiaQT4F11NPcQ8',
    steps: [
      { icon: 'fas fa-hand-pointer', label: 'Click Open Form' },
      { icon: 'fas fa-pen-to-square', label: 'Fill appointment details' },
      { icon: 'fas fa-envelope-circle-check', label: 'Get email confirmation' },
    ],
  },
}
